language: python
services:
- docker
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- echo "Test begin!!"
- pytest test/testBPI.py
- pytest test/testBTI.py

addons:
    ssh_known_hosts: 51.15.196.143
before_deploy:
- openssl aes-256-cbc -K $encrypted_8ee8bcddcdd7_key -iv $encrypted_8ee8bcddcdd7_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  skip_cleanup: true
  provider: script
  script: ssh 51.15.196.143 "sh ./deploy.sh"
  on:
    branch: integration
    python: '3.5'

