language: python
python:
    - "3.5"

# dependencies install
install:
    - pip install -r requirements.txt

# testing
script:
    - echo "Test begin!!"
    - pytest test/testBPI.py
    - pytest test/testBTI.py

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master
    python: '3.5'
