version: '2'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile/Dockerfile.${APP_ENV_CONFIG}
        networks:
            - backend
        volumes:
            - ./app:/app/
        
    db:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
        networks:
            - frontend
            - backend
        expose:
            - 9200
            - 9300
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    view:
        image: docker.elastic.co/kibana/kibana-oss:6.2.1
        networks:
            - frontend
        ports:
            - 80:5601
        expose:
            - 5061
        volumes:
            - ./kibana/config/:/usr/share/kibana/config:ro
        depends_on:
            - db
networks:
    frontend:
    backend:
