version: '2'
services:
    app:
        build:
            context: .
        networks:
            - backend
        volumes:
            # TODO remove this in production!
            - ./app:/app/
        depends_on:
            - db
    db:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
        networks:
            - frontend
            - backend
        expose:
            - 9200
            - 9300
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
            - ./elasticsearch/data:/usr/share/elasticsearch/data
    view:
        image: docker.elastic.co/kibana/kibana-oss:6.2.3
        networks:
            - frontend
        ports:
            - $KIBANA_PORT:5601
        expose:
            - 5061
        volumes:
            - ./kibana/config/:/usr/share/kibana/config:ro
        depends_on:
            - db
networks:
    frontend:
    backend:
