version: '2.0'
services:
    app:
        build:
            context: app
        networks:
            - kafka_net
    producer:
        build:
            context: app
        command: 'python src/BitcoinTxIndex_historicalProducer.py'
        networks:
            - kafka_net
    zookeeper:
        image: wurstmeister/zookeeper
        expose:
            - 2181
        environment:
            ZOOKEEPER_CLIENT_PORTY: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - kafka_net
    kafka:
        image: wurstmeister/kafka
        expose:
            - 9092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka/9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 36000
            LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER: INFO, authorizerAppender
        depends_on:
            - zookeeper
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - kafka_net
networks:
    kafka_net:
